# Generated by Django 4.2.7 on 2025-11-22 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alert_type', models.CharField(choices=[('TIRE_WEAR', 'Tire Wear'), ('FUEL_LOW', 'Low Fuel'), ('WEATHER_CHANGE', 'Weather Change'), ('STRATEGY_OPPORTUNITY', 'Strategy Opportunity'), ('COMPETITOR_THREAT', 'Competitor Threat'), ('SYSTEM_WARNING', 'System Warning')], max_length=50)),
                ('condition', models.JSONField()),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20)),
                ('message_template', models.TextField()),
                ('action_template', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('TIRE_WEAR', 'Tire Wear'), ('FUEL_LOW', 'Low Fuel'), ('WEATHER_CHANGE', 'Weather Change'), ('STRATEGY_OPPORTUNITY', 'Strategy Opportunity'), ('COMPETITOR_THREAT', 'Competitor Threat'), ('SYSTEM_WARNING', 'System Warning')], max_length=50)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('recommended_action', models.TextField(blank=True)),
                ('triggered_by', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='telemetry.vehicle')),
            ],
        ),
    ]
