# Generated by Django 4.2.7 on 2025-11-22 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lap_number', models.IntegerField()),
                ('lap_time', models.DurationField()),
                ('sector1_time', models.DurationField(blank=True, null=True)),
                ('sector2_time', models.DurationField(blank=True, null=True)),
                ('sector3_time', models.DurationField(blank=True, null=True)),
                ('speed', models.FloatField(help_text='Speed in km/h')),
                ('rpm', models.IntegerField()),
                ('gear', models.IntegerField()),
                ('throttle', models.FloatField(help_text='Throttle percentage')),
                ('brake', models.FloatField(help_text='Brake percentage')),
                ('position', models.IntegerField()),
                ('gap_to_leader', models.FloatField(help_text='Gap in seconds')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('team', models.CharField(max_length=100)),
                ('driver', models.CharField(max_length=100)),
                ('vehicle_id', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_temperature', models.FloatField()),
                ('air_temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('pressure', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('wind_direction', models.FloatField()),
                ('rainfall', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TireTelemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_left_temp', models.FloatField(blank=True, null=True)),
                ('front_right_temp', models.FloatField(blank=True, null=True)),
                ('rear_left_temp', models.FloatField(blank=True, null=True)),
                ('rear_right_temp', models.FloatField(blank=True, null=True)),
                ('front_left_pressure', models.FloatField(blank=True, null=True)),
                ('front_right_pressure', models.FloatField(blank=True, null=True)),
                ('rear_left_pressure', models.FloatField(blank=True, null=True)),
                ('rear_right_pressure', models.FloatField(blank=True, null=True)),
                ('telemetry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='telemetry.telemetrydata')),
            ],
        ),
        migrations.AddField(
            model_name='telemetrydata',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telemetry.vehicle'),
        ),
        migrations.AddIndex(
            model_name='telemetrydata',
            index=models.Index(fields=['vehicle', 'lap_number'], name='telemetry_t_vehicle_a56577_idx'),
        ),
        migrations.AddIndex(
            model_name='telemetrydata',
            index=models.Index(fields=['timestamp'], name='telemetry_t_timesta_301571_idx'),
        ),
    ]
