# Generated by Django 4.2.7 on 2025-11-22 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TireStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_laps_remaining', models.IntegerField()),
                ('degradation_rate', models.FloatField()),
                ('optimal_change_lap', models.IntegerField()),
                ('confidence', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telemetry.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='PitStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_lap', models.IntegerField()),
                ('confidence', models.FloatField()),
                ('strategy_type', models.CharField(choices=[('EARLY', 'Early Stop'), ('MIDDLE', 'Middle Stop'), ('LATE', 'Late Stop'), ('UNDERCUT', 'Undercut'), ('OVERCUT', 'Overcut')], max_length=20)),
                ('reasoning', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telemetry.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='FuelStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_fuel', models.FloatField()),
                ('predicted_laps_remaining', models.IntegerField()),
                ('consumption_rate', models.FloatField()),
                ('need_to_conserve', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telemetry.vehicle')),
            ],
        ),
    ]
