"""
Django settings for road_sense_service project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

# Start Websocket Server
# daphne -b 0.0.0.0 -p 8000 road_sense_service.asgi:application


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

# Determine environment
IS_PRODUCTION = True #os.environ.get('PRODUCTION', 'false').lower() == 'true'

# Security settings for production
if IS_PRODUCTION:
    # DEBUG = False
    # ALLOWED_HOSTS = [
    #     "neuraplay-service-930102180917.us-central1.run.app",
    #     "localhost",
    #     "127.0.0.1",
    # ]
    
    # Use environment variable for Redis in production
    REDIS_URL = os.environ.get('REDIS_URL', 'redis://localhost:6379/0')
else:
    DEBUG = True
    # ALLOWED_HOSTS = ["localhost", "127.0.0.1"]
    REDIS_URL = 'redis://localhost:6379/0'


# ALLOWED_HOSTS = []

PORT = int(os.environ.get("PORT", 8080))


ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    'road-sense-app.vercel.app',
    'road-sense-service-930102180917.us-central1.run.app',
    '.run.app',
    '.vercel.app',
    # '0.0.0.0',
    # '127.0.0.1:3000',  # Your Next.js frontend
    # 'localhost:3000',
]

# CORS settings
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:3000",
#     "http://127.0.0.1:3000",
# ]

# CSRF_USE_SESSIONS = True

# CSRF_COOKIE_HTTPONLY = True

CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'http://localhost:8000',
    "http://127.0.0.1:3000",
    "http://127.0.0.1:8000",
    'https://road-sense-app.vercel.app',
    'https://road-sense-service-930102180917.us-central1.run.app',
    # 'http://192.168.42.95:3000',
    # 'http://localhost:8080'
]


CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    'https://road-sense-app.vercel.app',
    'https://road-sense-service-930102180917.us-central1.run.app',
]

# CSRF_COOKIE_SECURE = False  # Must match SESSION_COOKIE_SECURE
# CSRF_COOKIE_HTTPONLY = False
# CSRF_COOKIE_HTTPONLY = True

# CSRF_COOKIE_SAMESITE = 'Lax'
# CSRF_COOKIE_SAMESITE = 'None'

# CSRF_USE_SESSIONS = True
# CSRF_COOKIE_NAME = 'csrftoken'
# CSRF_HEADER_NAME = 'HTTP_X_CSRFTOKEN'
# CSRF_USE_SESSIONS = False

# CSRF_COOKIE_SAMESITE = "None"
# CSRF_COOKIE_SECURE = False
# CSRF_COOKIE_HTTPONLY = False



# CORS_EXPOSE_HEADERS = ['Set-Cookie']
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]


# # DEVELOPMENT SETTINGS
# # settings.py - MUST HAVE THESE
# SESSION_ENGINE = 'django.contrib.sessions.backends.db'
# SESSION_COOKIE_SAMESITE = 'Lax'  # or 'None' for cross-domain
# SESSION_COOKIE_SECURE = False  # True in production with HTTPS
# SESSION_COOKIE_HTTPONLY = True
# SESSION_COOKIE_AGE = 1209600  # 2 weeks in seconds
# SESSION_COOKIE_NAME = 'sessionid'


# # CSRF settings
# CSRF_COOKIE_SAMESITE = 'Lax'
# CSRF_COOKIE_SECURE = False  # True in production
# CSRF_COOKIE_HTTPONLY = False  # Let JavaScript read it
# CSRF_USE_SESSIONS = False
# CSRF_COOKIE_NAME = 'csrftoken'






# PRODUCTION SETTINGS
# settings.py - PRODUCTION VERSION
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_SAMESITE = 'None'  # 'None' for cross-domain in production
SESSION_COOKIE_SECURE = True  # True in production with HTTPS
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_AGE = 1209600  # 2 weeks in seconds
SESSION_COOKIE_NAME = 'sessionid'


# CSRF settings
CSRF_COOKIE_SAMESITE = 'None'  # 'None' for cross-domain
CSRF_COOKIE_SECURE = True  # True in production
CSRF_COOKIE_HTTPONLY = False  # Let JavaScript read it
CSRF_USE_SESSIONS = False
CSRF_COOKIE_NAME = 'csrftoken'










# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'corsheaders',
    'channels',

    'telemetry.apps.TelemetryConfig',
    'strategy.apps.StrategyConfig',
    'analytics.apps.AnalyticsConfig',
    'alerts.apps.AlertsConfig',
    'accounts.apps.AccountsConfig',


]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'road_sense_service.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),  # ← Add this line
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    #  ADD THIS FOR DEVELOPMENT:
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',  # Temporary for debugging
    ],
}


# REST_FRAMEWORK = {
#     'DEFAULT_AUTHENTICATION_CLASSES': [
#         'rest_framework.authentication.SessionAuthentication',
#     ],
#     'DEFAULT_PERMISSION_CLASSES': [
#         'rest_framework.permissions.IsAuthenticated',
#     ],
#     'DEFAULT_RENDERER_CLASSES': [
#         'rest_framework.renderers.JSONRenderer',
#     ],
#     'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
#     'PAGE_SIZE': 20,
    
#     # ADD THIS FOR DEVELOPMENT:
#     'DEFAULT_PERMISSION_CLASSES': [
#         'rest_framework.permissions.AllowAny',  # Temporary for debugging
#     ],
# }


# SESSION_COOKIE_AGE = 3600  # 1 hour
# SESSION_COOKIE_HTTPONLY = True
# SESSION_COOKIE_SECURE = not DEBUG  # HTTPS only in production
# Session settings
# SESSION_COOKIE_SAMESITE = 'Lax'
# SESSION_COOKIE_DOMAIN = None  
# SESSION_COOKIE_SAMESITE = 'None'
# SESSION_COOKIE_SAMESITE = 'Lax'


# SESSION_COOKIE_SAMESITE = "None"
# SESSION_COOKIE_SECURE = True  # Local dev (HTTP)
# SESSION_COOKIE_HTTPONLY = False




# SESSION_COOKIE_SECURE = False  # Set to True in production with HTTPS


AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]


WSGI_APPLICATION = 'road_sense_service.wsgi.application'

ASGI_APPLICATION = 'road_sense_service.asgi.application'


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': os.environ.get('POSTGRES_DB'),           
#         'USER': os.environ.get('POSTGRES_USER'),        
#         'PASSWORD': os.environ.get('POSTGRES_PASSWORD'),     
#         'HOST': os.environ.get('POSTGRES_HOST'),               
#         'PORT': os.environ.get('POSTGRES_PORT'),              
#     }
# }


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('SUPABASE_POSTGRES_DB'),           
        'USER': os.environ.get('SUPABASE_POSTGRES_USER'),        
        'PASSWORD': os.environ.get('SUPABASE_POSTGRES_PASSWORD'),     
        'HOST': os.environ.get('SUPABASE_POSTGRES_HOST'),               
        'PORT': os.environ.get('SUPABASE_POSTGRES_PORT'), 
        'OPTIONS': {
            'sslmode': 'require',
        },                   
    }
}

DATABASE_SCHEMAS = {
    'default': 'road_sense_schema'
}


CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [os.environ.get('REDIS_URL', 'redis://localhost:6379')],
        },
    },
}

# Channel layers for production
# if IS_PRODUCTION:
#     CHANNEL_LAYERS = {
#         "default": {
#             "BACKEND": "channels_redis.core.RedisChannelLayer",
#             "CONFIG": {
#                 "hosts": [REDIS_URL],
#             },
#         },
#     }
# else:
#     CHANNEL_LAYERS = {
#         "default": {
#             "BACKEND": "channels.layers.InMemoryChannelLayer"
#         }
#     }



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


AUTH_USER_MODEL = 'accounts.User'

LOGIN_URL = '/api/accounts/auth/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Authentication
# LOGIN_REDIRECT_URL = '/'
# LOGOUT_REDIRECT_URL = '/'

# ML Models configuration
ML_MODELS_DIR = os.path.join(BASE_DIR, 'ml_models')

STATIC_URL = 'static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://localhost:6379/0')
# CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')

# Celery Configuration for production
CELERY_BROKER_URL = os.environ.get('REDIS_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('REDIS_URL', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

